#!/bin/bash
# rrc.sh - restore rc files in home
#
# BinLi (binli at opensuse.org)
#
PWD=`pwd`
RCDIR=$PWD/homerc
BINDIR=$PWD/bin
HOMEDIR=~/
HOMEBINDIR=~/bin
i=1 # the resource number

if [ -d $RCDIR ]; then
	LIST=`ls $RCDIR`
fi

if [ -z $LIST ]; then
	echo "No files in homerc directory!\n"
fi

for rcfile in $LIST
do
	dotrc=$HOMEDIR.$rcfile
	echo -e "$i) Restore the $dotrc..."
	if [ -L $dotrc -o -e $dotrc ]; then
		echo -e "$dotrc already exist!"
		echo -e "Do you wanna overwrite it?(y/n)"
		read OPT
		if [ $OPT = "y" ]; then 
			echo -e "Overwrite $dotrc now..."
			ln -sf $RCDIR/$rcfile $dotrc
		else
			echo -e "Skip $dotrc settting."
		fi
	else
		echo -e "Create $dotrc link now..."
		ln -s $RCDIR/$rcfile $dotrc
	fi
	let "i+=1"
done

# link all the file in bin/ into ~/bin/
if [ -d $BINDIR ]; then
	BIN_LIST=`ls $BINDIR`
fi

if [ -z $BIN_LIST ]; then
	echo "No files in bin directory!\n"
fi

for binfile in $BIN_LIST
do
	homebin=$HOMEBINDIR/$binfile
	echo -e "$i) Restore the $binfile..."
	if [ -L $homebin ]; then
		echo -e "$homebin already exist!"
		echo -e "Do you wanna overwrite it?(y/n)"
		read OPT
		if [ $OPT = "y" ]; then 
			echo -e "Overwrite $homebin now..."
			ln -sf $BINDIR/$binfile $homebin
		else
			echo -e "Skip $dotrc settting."
		fi
	else
		echo -e "Create $homebin link now..."
		ln -s $BINDIR/$binfile $homebin
	fi
	let "i+=1"
done

# Merge the bashrc into .bashrc, include PATH and PS1
if [ -e $HOMEDIR.bashrc ]; then
	echo -e "Merge the bashrc..."
	grep "export PATH" $HOMEDIR.bashrc || cat $RCDIR/bashrc >> $HOMEDIR.bashrc
else
	echo -e "Link the bashrc..."
	ln -s $RCDIR/bashrc $HOMEDIR.bashrc
fi
