#!/bin/bash
# rrc.sh - restore rc files in home
#
# BinLi (binli at opensuse.org)
#
PWD=`pwd`
RCDIR=$PWD/homerc
BINDIR=$PWD/bin
HOMEDIR=~/
HOMEBINDIR=~/bin
PREREQ=`cat debian.package.list`
i=1 # the resource number

if [ -d $RCDIR ]; then
	LIST=`ls $RCDIR`
fi

sudo apt-get update
for package in $PREREQ
do
	echo "apt-get install -y --force-yes $package"
	sudo apt-get install -y --force-yes $package
done

for rcfile in $LIST
do
	dotrc=$HOMEDIR.$rcfile
	echo -e "$i) Restore the $dotrc..."
	if [ -L $dotrc -o -e $dotrc ]; then
		echo -e "$dotrc already exist!"
		echo -e "Do you wanna overwrite it?(y/n)"
		read OPT
		if [ $OPT = "y" ]; then 
			echo -e "Overwrite $dotrc now..."
			ln -sf $RCDIR/$rcfile $dotrc
		else
			echo -e "Skip $dotrc settting."
		fi
	else
		echo -e "Create $dotrc link now..."
		ln -s $RCDIR/$rcfile $dotrc
	fi
	let "i+=1"
done

VIM_PLUGIN=$RCDIR/vim/plugin
mkdir -p $VIM_PLUGIN
wget http://www.vim.org/scripts/download_script.php?src_id=16171 -O $VIM_PLUGIN/DirDiff.vim

# for msmtprc we need remove group and other read permission.

# link all the file in bin/ into ~/bin/
if [ -d $BINDIR ]; then
	BIN_LIST=`ls $BINDIR`
fi

# the $HOME/bin not exist in ubuntu, so need to create a new one
if [ ! -d $HOMEBINDIR ]; then
	mkdir $HOMEBINDIR
fi

for binfile in $BIN_LIST
do
	homebin=$HOMEBINDIR/$binfile
	echo -e "$i) Restore the $binfile..."
	if [ -L $homebin ]; then
		echo -e "$homebin already exist!"
		echo -e "Do you wanna overwrite it?(y/n)"
		read OPT
		if [ $OPT = "y" ]; then 
			echo -e "Overwrite $homebin now..."
			ln -sf $BINDIR/$binfile $homebin
		else
			echo -e "Skip $homebin settting."
		fi
	else
		echo -e "Create $homebin link now..."
		ln -s $BINDIR/$binfile $homebin
	fi
	let "i+=1"
done

ISSUE=`cat /etc/issue | awk '{print $1}'`

# if we use Ubuntu, skip some operation.
if [ $ISSUE = "Ubuntu" ]; then
	echo "Bye! Welcome use rrc in Ubuntu"
	exit 0;
fi

if [ $ISSUE = "Debian" ]; then
	echo "Bye! Welcome use rrc in Debian"
	exit 0;
fi

# Merge the bashrc into .bashrc, include PATH and PS1
if [ -e $HOMEDIR.bashrc ]; then
	echo -e "Merge the bashrc..."
	grep "export PATH" $HOMEDIR.bashrc || cat $RCDIR/bashrc >> $HOMEDIR.bashrc
else
	echo -e "Link the bashrc..."
	ln -s $RCDIR/bashrc $HOMEDIR.bashrc
fi

echo "Bye! Welcome use rrc in openSUSE"
