alias vd='vimdiff'
alias sc='screen -D -R'
alias l='ls -alF'
alias e='exit'
alias s='cd /source'
alias gr="gnome-shell --replace"
alias agi='sudo apt-get install'
alias acs='apt-cache search'

#below is in openSUSE
alias o='less'
alias ..='cd ..'
alias ...='cd ../..'
alias cd..='cd ..'
alias md='mkdir -p'
alias rd='rmdir'
